#!/usr/bin/env python

from __future__ import print_function

import sys, os, time

# Tkinter changed capitalization from Python 2 to Python 3.
try:
    import tkinter
except ModuleNotFoundError:
    import Tkinter as tkinter

# Callback for key events:
def keyEvent(event):
    # print(event.char, event.keysym, event.keycode)
    if event.char == 'q' or event.keysym == 'Return':
        sys.exit(0)

def Usage():
    print("Usage:", sys.argv[0], "minutes message")
    sys.exit(1)

def showAlert(message):
    # This is supposed to show a dialog, but tkMessageBox doesn't exist:
    # tkMessageBox.showwarning("hello", message)

    # Try to beep a bit, even though that doesn't work on some distros:
    print("")
    # print message

    root = tkinter.Tk()

    button = tkinter.Button(root, text=message,
                            bg="red", activebackground="red",
                            fg="white", activeforeground="white",
                            font=("Sans", 40, "bold"),
                            command=quit)

    # Make sure the window is at least as big as the screen:
    button.pack(ipadx=root.winfo_screenwidth()/2,
                ipady=root.winfo_screenheight()/2)

    # Apparently we can't bind key events to a button, only to the root:
    root.bind("<Key>", keyEvent)

    root.mainloop()

# main: read the runtime arguments.
if __name__ == '__main__':

    try:
      sleeptime = float(sys.argv[1]) * 60
    except ValueError:
      Usage()

    if len(sys.argv) > 2:
      message = ' '.join(sys.argv[2:])
    else:
      message = "Wake up!"

    print("Sleeping for", sleeptime, "seconds with message:", message)

    # Return control to the shell before sleeping:
    rc = os.fork()
    if rc:
        sys.exit(0)

    time.sleep(sleeptime)

    showAlert(message)
