#!/usr/bin/env python

# TODO: Group fonts in the same family into one entry in the list.
# TODO: See if it's possible to query for language and screen out
#       fonts not in the current language.

# fontasia 0.95:
# List all fonts on the system and let the user group them into categories.
#
# Can be run as a standalone script, or as a GIMP 2.x plug-in font chooser
# (where it shows up as Windows->Fontasia).

#
# Contributors: Akkana Peck, Mikael Magnusson, Michael Schumacher
#
# More info on fontasia: http://shallowsky.com/software/fontasia

# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranties of
# MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.


import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, Gdk
# gi.require_version('Pango', '1.0')
from gi.repository import Pango

import re
import subprocess
import os

# Maximum number of faces (in the Pango sense, e.g. italic, bold, extralight)
# to show for a given font family:
MAX_FACES = 27


class FontasiaApp(Gtk.Window):

    # CSS for the category buttons. No longer needed, but left in
    # as an example of how to apply CSS if needed.
    #     CSS = '''
    # .highlightbtn { background-image: none; background-color: #; }
    # '''

    def __init__(self):
        super(FontasiaApp, self).__init__()

        # This populates self.langs_by_family
        self.get_font_languages()

        # When the quit button is pressed we'll set the quit flag,
        # but won't actually quit -- the caller has to do that
        # after checking the selected font.
        self.quit = False

        self.ignore_callbacks = True

        # Pango seems to have no way to get a font family given its name,
        # so store all font families when we iterate through them,
        # which will happen in update_font_list().
        self.font_families = {}

        # No categories to start with
        self.default_fonts = []
        self.category_buttons = []
        self.facebuttons = []
        self.DEFAULT_TEXT = "The quick brown fox jumped over the lazy dog"
        self.preview_text = self.DEFAULT_TEXT
        self.DEFAULT_FONT_SIZE = 18
        self.fancy_list = True
        self.default_props = []

        # Items that will be remembered in the config file
        self.category_fontlists = []
        self.fontsize = self.DEFAULT_FONT_SIZE
        self.current_font = None

        # Default sizes: can be overridden in .config/fontasia/fontasia.conf

        self.win_width = 760
        self.win_height = 400
        self.preview_height = 56
        self.list_width = 250

        # Have we changed anything, so we need to rewrite the config file?
        self.modified = False

        self.set_border_width(8)
        self.connect("destroy", self.save_and_quit)
        self.set_title("Fontasia: Categorize your fonts")

        # Intercept Page Up/Down when focus is in the preview,
        # so you can scroll the list without needing to click in it first.
        self.connect("key-release-event", self.key_release)

        main_vbox = Gtk.VBox(spacing = 10)
        self.add(main_vbox)

        hbox = Gtk.HBox(spacing = 10)
        main_vbox.pack_start(hbox, expand=False, fill=True, padding=0)

        #
        # The preview
        #
        self.preview = Gtk.Entry()
        # The preview will be however wide the window is, saved from last time
        # self.preview.set_width_chars(45)

        self.preview.set_text(self.preview_text)
        # These don't work: I think because grab_focus_without_selecting()
        # (called in render_font()) sets the position to 0.
        # self.preview.select_region(-1, -1)
        # self.preview.set_position(-1)

        # Don't use fallbacks for characters not in the current font.
        # This apparently didn't work in Gtk2, and is deprecated in Gtk3.
        # al = Pango.AttrList()
        # al.insert(Pango.AttrFallback(False, 0, -1))
        # self.preview.get_layout().set_attributes(al)

        hbox.pack_start(self.preview, expand=True, fill=True, padding=0)

        # Quit button
        btn = Gtk.Button(label="Quit")
        hbox.pack_end(btn, expand=False, fill=True, padding=0)
        btn.connect("clicked", self.save_and_quit);

        #
        # Above the TreeView: selectors for which fonts to show
        #

        # Box to hold font size, view category etc.
        hbox = Gtk.HBox(spacing=10)
        main_vbox.pack_start(hbox, expand=False, fill=True, padding=0)

        # Checkbox for rendering fonts in the font list
        self.fancy_btn = Gtk.ToggleButton(label="Fancy list")
        self.fancy_btn.set_active(self.fancy_list)
        self.fancy_btn.connect("toggled", self.toggle_fancy_list_cb)
        hbox.pack_start(self.fancy_btn, expand=False, fill=True, padding=0)

        # Button to copy current font name
        # btn = Gtk.Button(label="Copy Font Name")
        # hbox.pack_end(btn, expand=False)
        # btn.connect("clicked", self.copy_font_name);

        # Font size
        label = Gtk.Label(label="Size:")
        hbox.pack_start(label, expand=False, fill=True, padding=0)

        adj = Gtk.Adjustment(value=self.fontsize, lower=1, upper=1000,
                             step_increment=1)
        self.sizespin = Gtk.SpinButton(adjustment=adj)
        self.sizespin.set_numeric(True)
        self.sizespin.connect("value-changed", self.choose_family);
        hbox.pack_start(self.sizespin, expand=False, fill=True, padding=0)

        #
        # View category menu
        #
        label = Gtk.Label(label="Show Category:")
        # This is supposed to right-align the label, but alas it does nothing
        # and is now deprecated in Gtk3:
        #label.set_alignment(1.0, .5)
        # This also doesn't right-align, but the docs are clear on that:
        # label.set_justify(Gtk.JUSTIFY_RIGHT)
        hbox.pack_start(label, expand=False, fill=True, padding=0)

        self.view_cat_combo = Gtk.ComboBoxText()
        hbox.pack_start(self.view_cat_combo, expand=False, fill=True, padding=0)
        self.cat_combo_id = self.view_cat_combo.connect("changed",
                                                        self.combochanged)

        #
        # View Property menu
        #
        label = Gtk.Label(label="Show Fonts with Property:")
        # This is supposed to right-align the label, but alas it does nothing
        # and is now deprecated in Gtk3:
        #label.set_alignment(1.0, .5)
        # This also doesn't right-align, but the docs are clear on that:
        # label.set_justify(Gtk.JUSTIFY_RIGHT)
        hbox.pack_start(label, expand=False, fill=True, padding=0)

        # Get a list of all languages supported by fonts on the system
        all_langs = []
        for fam in self.langs_by_family:
            for lang in self.langs_by_family[fam]:
                if lang not in all_langs:
                    all_langs.append(lang)
        all_langs.sort()
        proplist = [ ['monospace', 'Monospace'],
                     ['variable', 'Variable Space'],
                     ['lang:en', 'English'],
                     ['excludeCJK', 'Exclude CJK'],
                     ['lang:none', 'Language unspecified']
                   ]
        for lang in all_langs:
            if lang != 'en' and lang != 'none':
                proplist.append(('lang:' + lang, lang))
        self.view_prop_menu = ToggleOptionsMenu(proplist,
                                                self.view_prop_changed,
                                                max_visible=16)
        hbox.pack_start(self.view_prop_menu, expand=False, fill=True, padding=0)

        # The main hbox contains the treeview font list,
        # plus a right pane with a lot of info about the current font.
        main_hbox = Gtk.HBox(spacing = 10)
        main_vbox.add(main_hbox)

        #
        # Left pane: the font list, a TreeView backed by a ListStore
        #
        self.sw = Gtk.ScrolledWindow()
        self.sw.set_policy(Gtk.PolicyType.AUTOMATIC, Gtk.PolicyType.AUTOMATIC)

        context = self.create_pango_context()
        self.all_families = context.list_families()
        self.store = Gtk.ListStore(str)

        self.treeview = Gtk.TreeView(model=self.store)
        # XXX deprecated
        # self.treeview.set_rules_hint(True)
        self.store.set_sort_column_id(0, Gtk.SortType.ASCENDING)

        # Try to allow multi-selection:
        # https://askubuntu.com/a/294035 suggests setting can_focus helps,
        # but it doesn't
        self.treeview.set_can_focus(True)
        # and this used to work, but no longer does:
        selection = self.treeview.get_selection()
        selection.set_mode(Gtk.SelectionMode.MULTIPLE)

        self.treeview.connect("button-press-event",
                              self._on_treeview_button_press)

        # This doesn't work with multiple selection:
        # self.treeview.connect("cursor-changed", self.choose_family);
        # but this does:
        selection.connect("changed", self.choose_family);

        self.sw.add(self.treeview)

        self.create_column(self.treeview)

        main_hbox.pack_start(self.sw, expand=False, fill=True, padding=0)

        #
        # Right pane: details on the current font
        #
        vbox = Gtk.VBox(spacing=15)
        main_hbox.pack_start(vbox, expand=True, fill=True, padding=0)

        #
        # Categories current font is in
        #
        frame = Gtk.Frame(label="In User Categories")
        frame.set_shadow_type(Gtk.ShadowType.IN)
        vbox.pack_start(frame, expand=False, fill=True, padding=0)
        fvbox = Gtk.VBox(spacing=15)
        fvbox.props.margin_left = 10
        fvbox.props.margin_right = 10
        fvbox.props.margin_top = 10
        fvbox.props.margin_bottom = 10
        frame.add(fvbox)

        # The category buttons
        self.catbuttonbox = Gtk.FlowBox()
        fvbox.pack_start(self.catbuttonbox, expand=False, fill=True, padding=0)

        # Categories header row
        hbox = Gtk.HBox(spacing=8)
        fvbox.pack_start(hbox, expand=False, fill=True, padding=0)
        label = Gtk.Label(label="Add category:")
        hbox.pack_start(label, expand=False, fill=True, padding=0)

        entry = Gtk.Entry()
        entry.set_width_chars(20)
        hbox.pack_start(entry, expand=False, fill=True, padding=0)

        btn = Gtk.Button(label="Add category")
        hbox.pack_start(btn, expand=False, fill=True, padding=0)
        btn.set_sensitive(False)
        btn.connect("clicked", self.add_category, entry);
        # The entry and button are tied together:
        entry.connect("changed", self.new_cat_entry_changed, btn);

        #
        # Style area (what Pango calls faces):
        #
        frame = Gtk.Frame(label="Has Styles")
        # Shadow types don't currently seem to work, but leave it here
        # in case it ever starts working
        frame.set_shadow_type(Gtk.ShadowType.IN)
        vbox.pack_start(frame, expand=False, fill=True, padding=0)
        fvbox = Gtk.VBox(spacing=15)
        # There doesn't seem to be a way to set margin in general
        fvbox.props.margin_left = 10
        fvbox.props.margin_right = 10
        fvbox.props.margin_top = 10
        fvbox.props.margin_bottom = 10
        frame.add(fvbox)

        # A space for face buttons like Bold, Italic
        self.facebuttonbox = Gtk.FlowBox()
        fvbox.pack_start(self.facebuttonbox, expand=False, fill=True, padding=0)

        #
        # Apply the CSS: not currently used.
        #
        # self.css_provider = Gtk.CssProvider()
        # self.apply_CSS(FontasiaApp.CSS)

        # Not sure if this could be done earlier
        self.preview.get_style_context().add_class("preview")

        # Read the prefs file
        self.read_category_file()

        self.view_prop_menu.set_options(self.default_props)

        # Read in all system and user fonts and update the UI accordingly
        self.update_font_list(self.default_fonts)

        # Set size requests, now that we've read them from the config file:
        self.set_default_size(self.win_width, self.win_height)

        self.sw.set_size_request(self.list_width, -1)
        #self.sw.set_size_request(self.list_width, self.list_height)
        self.preview.set_size_request(-1, self.preview_height)

        # Done with UI, finish showing window
        self.show_all()

        # Setting size_requests earlier set the *minimum* size,
        # but we don't want to do that. So reset the size request
        # once the widgets have already been sized.
        # Alas, Gtk has no way to just set the size without
        # specifying a minimum; size_allocate() is a no-op.
        #self.sw.set_size_request(self.list_width, 1)
        #self.preview.set_size_request(-1, -1)

        self.ignore_callbacks = False

        # Try again to set multi-selection mode: sometimes it doesn't work
        selection.set_mode(Gtk.SelectionMode.MULTIPLE)

    def save_and_quit(self, widget=None):
        self.write_category_file()
        self.quit = True
        # Gtk.main_quit()

    def apply_CSS(self, newCSS: str):
        try:
            self.css_provider.load_from_data(newCSS.encode('UTF-8'))
        except gi.repository.GLib.GError as e:
            print("GTK Error applying CSS:", e, file=sys.stderr)
            print("CSS was:", newCSS, file=sys.stderr)
        context = Gtk.StyleContext()
        context.add_provider_for_screen(Gdk.Screen.get_default(),
                                        self.css_provider,
                                        Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)

    def key_release(self, widget, event):
        if event.keyval == Gdk.KEY_Page_Up \
           or event.keyval == Gdk.KEY_KP_Page_Up:
            adj = self.sw.get_vadjustment()
            new_value = adj.get_value() - adj.get_page_increment()
            adj.set_value(max(new_value, adj.get_lower()))
            return True
        elif event.keyval == Gdk.KEY_Page_Down \
             or event.keyval == Gdk.KEY_KP_Page_Down:
            adj = self.sw.get_vadjustment()
            new_value = adj.get_value() + adj.get_page_increment()
            adj.set_value(min(new_value, adj.get_upper() - adj.get_page_size()))
            return True
        return False

    def toggle_fancy_list_cb(self, widget):
        self.fancy_list = widget.get_active()
        self.toggle_fancy_list(self.fancy_list)
        # By default, each row won't change until it's moused over,
        # or maybe it might change at some random future time
        # for reasons I never figured out. Calling
        # self.update_font_list()
        # fixes it, but it's better to do it in an idle loop
        # so as not to block the UI:
        model = self.treeview.get_model()
        self._refresh_iter = model.get_iter_first()
        gi.repository.GLib.idle_add(self._refresh_chunk, model)

    def _refresh_chunk(self, model):
        count = 0
        while self._refresh_iter is not None and count < 50:
            path = model.get_path(self._refresh_iter)
            model.row_changed(path, self._refresh_iter)
            self._refresh_iter = model.iter_next(self._refresh_iter)
            count += 1
        return self._refresh_iter is not None  # True = reschedule, False = done

    def toggle_fancy_list(self, yesno):
        column = self.treeview.get_column(0)
        rendererText = column.get_cells()[0]
        if self.fancy_list:
            column.set_cell_data_func(rendererText, self.set_list_font)
        else:
            column.set_cell_data_func(rendererText, None)
            rendererText.set_property('font', None)

    def set_list_font(self, column, cell, model, iter, user_data):
        fontname = model.get_value(iter, 0)

        # If the font name ends with a number, we're in trouble --
        # Pango will try to interpret the number as a HUGE size.
        # Sample fonts to test: Math2, Math3,
        # Plain Cred 1978 from ttf-larabie-uncommon.
        # A few fonts still give width problems, like
        # Radios in Motion and Radios in Motion Hard.
        # Scriptina - Alternates and Coca-Cola.
        fontname = re.sub('[0-9]+$', '', fontname)

        cell.set_property('font', fontname)

    def create_column(self, treeView):
        rendererText = Gtk.CellRendererText()
        column = Gtk.TreeViewColumn("Font name", rendererText, text=0)
        column.set_sort_column_id(0)
        if self.fancy_list:
            column.set_cell_data_func(rendererText, self.set_list_font)
        treeView.set_search_column(0)
        treeView.append_column(column)

    def is_font_in_category(self, fontname, catname):
        for i in range(0, len(self.category_buttons)):
            if self.category_buttons[i].get_name() == catname:
                return ( fontname in self.category_fontlists[i] )
        return False

    def toggle_font_in_category(self, fontname, catname, set_on):
        for i in range(0, len(self.category_buttons)):
            if self.category_buttons[i].get_name() == catname:
                if set_on:
                    if fontname not in self.category_fontlists[i]:
                        self.category_fontlists[i].append(fontname)
                else:
                    if fontname in self.category_fontlists[i]:
                        self.category_fontlists[i].remove(fontname)
                return

    #
    # This is the callback from the font category togglebuttons.
    # It calls toggle_font_in_category.
    #
    def toggle_cur_font_in_cat(self, button, catname):
        # Get the rows corresponding with font families currently selected
        selection = self.treeview.get_selection()
        model, item = selection.get_selected_rows()

        # Read all the selected fonts, not just the first one:
        for x in item:
            fontname = model[x[0]][0]
            self.toggle_font_in_category(fontname, catname, button.get_active())
            # self.update_category_buttons(fontname)
        self.treeview.grab_focus()

    def view_prop_changed(self):
        self.update_font_list()

    # Update the View Categories combobox:
    def update_cats_menu(self):
        """Populate the user categories menu"""
        if self.cat_combo_id:
            self.view_cat_combo.handler_block(self.cat_combo_id)

        self.view_cat_combo.get_model().clear()
        # A recent Gtk3 change requires this or none of the combobox entries
        # will appear at all.
        self.view_cat_combo.set_entry_text_column(0)

        self.view_cat_combo.append_text("All fonts")

        for btn in self.category_buttons:
            catname = btn.get_name()
            item = Gtk.MenuItem(label=catname)
            self.view_cat_combo.append_text(catname)

        self.view_cat_combo.append_text("All in categories")
        self.view_cat_combo.append_text("All uncategorized")

        self.view_cat_combo.set_active(0)

        if self.cat_combo_id:
            self.view_cat_combo.handler_unblock(self.cat_combo_id)

    # How to get the active text from a combobox:
    def cur_category(self):
        model = self.view_cat_combo.get_model()
        active = self.view_cat_combo.get_active()
        if active < 0:
            return None
        return model[active][0]

    def combochanged(self, widget):
        curcat = self.cur_category()
        if curcat:
            self.update_font_list()

    def _on_treeview_button_press(self, treeview, event):
        if event.button != 1:
            return False
        if not event.state:
            # This doesn't get triggered, at least for me, because
            # GDK_MOD2_MASK is always set. That's NumLock.
            return False

        path_info = treeview.get_path_at_pos(int(event.x), int(event.y))
        if path_info is None:
            return False
        path, column, cell_x, cell_y = path_info
        selection = treeview.get_selection()

        if event.state & Gdk.ModifierType.SHIFT_MASK:
            anchor_path, _ = treeview.get_cursor()
            if anchor_path is not None:
                selection.select_range(anchor_path, path)
            else:
                selection.select_path(path)
            return True

        if event.state & Gdk.ModifierType.CONTROL_MASK:
            if selection.path_is_selected(path):
                selection.unselect_path(path)
            else:
                selection.select_path(path)
            return True

        return False  # not a ctrl-click: let GTK do its normal thing

    def update_font_list(self, selected_fonts=None):
        # Save the selected font(s), if any
        tvselection = self.treeview.get_selection()
        model, item = tvselection.get_selected_rows()
        if not selected_fonts:
            selected_fonts = []
            for x in item:
                selected_fonts.append(model[x[0]][0])

        catname = self.cur_category()
        if not catname:
            catname = "All fonts"
        special = (catname[0:3] == "All")
        if special:
            show_all = (catname == "All fonts")
            show_all_in_cats = (catname == "All in categories")
            show_all_not_in_cats = (catname == "All uncategorized")
        # if show_all or show_all_in_cats:
        #     for catbtn in self.category_buttons:
        #         catbtn.set_active(show_all_in_cats)

        # Create or clear the list store:
        self.store.clear()

        active_props = self.view_prop_menu.get_active_list()
        tvselection.unselect_all()

        self.font_families = {}
        for ff in self.all_families:
            fname = ff.get_name()

            # Pango doesn't seem to have any way to get the font family object
            # from its name. So store all families as a dictionary.
            self.font_families[fname] = ff

            # Should it be shown based on its properties?
            hide_font = False
            # Collect languages specified, if any
            languages = set()
            for prop in active_props:
                if prop.startswith('lang:'):
                    languages.add(prop[5:])
            for prop in active_props:
                if prop == 'monospace':
                    if not ff.is_monospace():
                        hide_font = True
                        break
                if prop == 'variable':
                    if not ff.is_variable():
                        hide_font = True
                        break
                if prop == 'excludeCJK':
                    if 'CJK' in fname:
                        hide_font = True
                        break
                if languages:
                    # fc-list doesn't list all the families pango sees,
                    # e.g. it doesn't see classes like 'Monospace'.
                    # If something wasn't in fc-list, show it.
                    if fname not in self.langs_by_family:
                        break

                    # Some fonts don't list languages,
                    # including a lot of the noto crap that's for
                    # specific languages, like cuneiform.
                    # By default, if you specify at least one language,
                    # fonts that don't specify a language won't be
                    # shown, but you can show them by checking
                    # Language unspecified.
                    if not self.langs_by_family[fname] \
                       and 'none' not in languages:
                        hide_font = True
                        break

                    # If there's no intersection between languages specified
                    # by the user and languages listed by fc-list,
                    # skip this font.
                    if not languages.intersection(
                            set(self.langs_by_family[fname])):
                        hide_font = True
                        break

            if hide_font:
                continue

            # Else not a special case. Just check for cat membership:
            if not special:
                if self.is_font_in_category(fname, catname):
                    self.store.append([fname])
                continue

            if show_all:
                self.store.append([fname])
                continue

            if show_all_in_cats:
                for catbtn in self.category_buttons:
                    if self.is_font_in_category(fname, catbtn.get_name()):
                        self.store.append([fname])
                        break

            if show_all_not_in_cats:
                is_in_cat = False
                for catbtn in self.category_buttons:
                    if self.is_font_in_category(fname, catbtn.get_name()):
                        is_in_cat = True
                        break
                if not is_in_cat:
                    self.store.append([fname])
                continue

        # Re-select anything that was selected before
        if selected_fonts:
            # Do this first before looping, otherwise set_cursor
            # will overwrite any multi-selection
            self.select_font_by_name(selected_fonts[0])
            first_path = None
            for row, treemodelrow in enumerate(self.store):
                if treemodelrow[0] in selected_fonts:
                    path = Gtk.TreePath.new_from_indices([row])
                    tvselection.select_path(path)
                    if first_path is None:
                        first_path = path
        # Control-click doesn't work in the treeview until focus is set there,
        # so it takes two control-clicks to add another selection,
        # even though regular left click works the first time.
        # This fixes it, but at the cost of stealing focus which ought
        # to be in the text field:
        # self.treeview.grab_focus()

        # Reset all the button colors, since nothing is selected now
        # (eventually might be nice to retain the old selection,
        # if it's still in the list):
        # XXX Should change this to call set_active()
        for btn in self.category_buttons:
            self.change_button_color(btn, False)

    def select_font_by_name(self, fontname):
        """Select the treeview row matching the given font name, if any.
        """
        # OMG, it's so incredibly difficult and undocumented
        # to auto-select a row in a treeview!

        # Iterate through the treeview
        for row, treemodelrow in enumerate(self.store):
            # treemodelrow is a gi.overrides.Gtk.TreeModelRow
            # treemodelrow[0] is the name of the font
            if treemodelrow[0] == fontname:
                # print("Matched line", row, treemodelrow[0])
                self.treeview.set_cursor(row, self.treeview.get_column(0),
                                         False)
                self.treeview.scroll_to_cell(row)
                return

            treemodelrow = treemodelrow.get_next()

    #
    # Lines in the category file look like:
    # catname: font, font, font ...
    #
    def read_category_file(self) :
        try:
            from win32com.shell import shellcon, shell
            homedir = shell.SHGetFolderPath(0, shellcon.CSIDL_APPDATA, 0, 0)
        except ImportError:
            homedir = os.getenv("HOME")

        self.cat_file_name = os.path.join(homedir, ".config", "fontasia",
                                          "fontasia.conf")

        filename = self.cat_file_name
        if not os.access(filename, os.R_OK):
            filename = "/etc/xdg/fontasia/defaults"
        try:
            catfp = open(filename, "r")
            while 1:
                line = catfp.readline()
                if not line: break
                line = line.strip()
                if line[0] == '#':     # Skip comments
                    continue

                if line[0:4] == "set ":
                    varval = line[4:].strip().split("=")
                    if varval[0] == "string":
                        self.preview.set_text(varval[1].strip())
                        continue

                    if varval[0] == "fontname":
                        self.default_fonts = varval[1].split(',')
                        continue

                    if varval[0] == "fontsize":
                        self.fontsize = int(varval[1])
                        self.sizespin.set_value(self.fontsize)
                        continue
                    if varval[0] == "fancy_list":
                        self.fancy_list = (varval[1] == "True")
                        self.fancy_btn.set_active(self.fancy_list)
                        self.toggle_fancy_list(self.fancy_list)
                        continue
                    if varval[0] == "win_width":
                        self.win_width = int(varval[1])
                        continue
                    if varval[0] == "win_height":
                        self.win_height = int(varval[1])
                        continue
                    if varval[0] == "preview_height":
                        self.preview_height = int(varval[1])
                        continue
                    if varval[0] == "list_width":
                        self.list_width = int(varval[1])
                        continue
                    if varval[0] == "props":
                        self.default_props = varval[1].split(',')
                        continue

                    # Arguably should save any other values
                    # for writing back to the file even though
                    # we don't understand any others
                    else:
                        print("Skipping unknown setting", varval[0])
                        continue

                colon = line.find(":")
                if colon < 0:
                    print("Didn't understand line", line, end='')
                    continue
                catname = line[0:colon].strip()
                self.add_category(catname)
                line = line[colon+1:].strip()
                fonts = line.split(",")
                for font in fonts:
                    font = font.strip()
                    self.toggle_font_in_category(font, catname, True)
            catfp.close()
            self.update_cats_menu()

        except IOError:
            print("No fontasia conf file yet -- Welcome to fontasia!")

            return

    def write_category_file(self):
        catdir = os.path.dirname(self.cat_file_name)
        if not os.path.exists(catdir):
            os.mkdir(catdir)
        catfp = open(self.cat_file_name, "w")
        txt = self.preview.get_text()
        if txt != self.DEFAULT_TEXT:
            try:
                print("set string=" + txt, file=catfp)
            except:
                print("Problem saving the string; reverting to default string")

        curfonts = self.get_selected_fonts()
        if curfonts:
            print("set fontname=" + ','.join(curfonts), file=catfp)

        fontsize = self.sizespin.get_value()
        if fontsize != self.DEFAULT_FONT_SIZE:
            print("set fontsize=" + str(int(fontsize)), file=catfp)

        # Get the current sizes for the list and the preview
        alloc = self.get_allocation()
        print("set win_width=" + str(alloc.width), file=catfp)
        print("set win_height=" + str(alloc.height), file=catfp)
        alloc = self.sw.get_allocation()
        print("set list_width=" + str(alloc.width), file=catfp)
        alloc = self.preview.get_allocation()
        print("set preview_height=" + str(alloc.height), file=catfp)

        if not self.fancy_list:
            print("set fancy_list=False", file=catfp)

        for i in range(0, len(self.category_buttons)):
            catname = self.category_buttons[i].get_name()
            if catname.startswith('_'):
                continue
            print(catname + ":", ', '.join(self.category_fontlists[i]),
                  file=catfp)

        active_props = self.view_prop_menu.get_active_list()
        print("set props=" + ','.join([prop for prop in active_props]), file=catfp)

        catfp.close()
        print("Saved to", self.cat_file_name)

    def new_cat_entry_changed(self, entry, btn):
        btn.set_sensitive(entry.get_text_length() > 0)

    def category_exists(self, catname):
        for btn in self.category_buttons:
            if btn.get_name() == catname:
                return True
        return False

    def add_category(self, newcat, entry=None):
        if entry:
            newcat = entry.get_text()

        # Make sure we don't already have this category:
        if (self.category_exists(newcat)):
            return

        btn = Gtk.ToggleButton(label=newcat)
        btn.set_name(newcat)
        # self.catbuttonbox.addButton(btn)
        self.catbuttonbox.insert(btn, position=-1)
        btn.connect("clicked", self.toggle_cur_font_in_cat, newcat);
        btn.show()

        self.category_buttons.append(btn)
        self.category_fontlists.append([])
        self.update_cats_menu()

        # If any fonts are selected, most likely the user wants them
        # added to the new category.
        self.toggle_cur_font_in_cat(btn, newcat)

        if (entry):
            entry.set_text("")

    #
    # Callback for the main toggle buttons down the right half of the window.
    #
    #def category_toggle(self, widget, catname):
    #    self.update_font_list()

    def change_button_color(self, btn, yesno):
        if yesno:
            btn.get_style_context().add_class("highlightbtn")
        else:
            btn.get_style_context().remove_class("highlightbtn")

    def update_category_buttons(self, fontname):
        self.ignore_callbacks = True
        for i in range(0, len(self.category_buttons)):
            if fontname in self.category_fontlists[i]:
                self.category_buttons[i].set_active(True)
            else:
                self.category_buttons[i].set_active(False)

        self.ignore_callbacks = False

    def get_cur_font_family(self):
        selection = self.treeview.get_selection()
        model, item = selection.get_selected_rows()

        if not item:
            if self.current_font:
                return self.current_font
            return None

        self.current_fonts = model[item[0][0]][0]

        # Only render the first font.
        return model[item[0][0]][0]

    def get_selected_fonts(self):
        selection = self.treeview.get_selection()
        model, item = selection.get_selected_rows()

        if not item:
            return []

        return [model[it[0]][0] for it in item]

    def copy_font_name(self, widget):
        """Copy current font face name to both PRIMARY and CLIPBOARD"""
        curfont = self.get_cur_font_family()

        atom = Gdk.atom_intern('PRIMARY', True)
        clipboard = widget.get_clipboard(atom)
        clipboard.set_text(curfont, -1)

        atom = Gdk.atom_intern('CLIPBOARD', True)
        clipboard = widget.get_clipboard(atom)
        clipboard.set_text(curfont, -1)

    def render_font(self, family, face):
        context = self.preview.get_pango_context()
        if face:
            fontstr = "%s %s %d" % (family.get_name(), face.get_face_name(),
                                    self.fontsize)
        else:
            fontstr = family.get_name()

        fontdesc = Pango.font_description_from_string(fontstr)
        # print("fontdesc:", fontdesc)
        # print("fontdesc str:", fontdesc.to_string())
        # print("family:", fontdesc.get_family())
        # print("size:", fontdesc.get_size())
        # print("weight:", fontdesc.get_weight())
        # print("stretch:", fontdesc.get_stretch())
        # print("style:", fontdesc.get_style())
        # print("variant:", fontdesc.get_variant())
        # print("variations:", fontdesc.get_variations())

        # This works better than context.set_font_description,
        # but it's deprecated:
        # self.preview.modify_font(fontdesc)

        # Another, less reliable way to change an entry's font --
        # but it requires getting context = self.preview.get_pango_context()
        # earlier, before creating the new fontdesc, for some reason.
        context.set_font_description(fontdesc)

        # It's not good to grab the focus like this -- the user might
        # want focus somewhere else, like in the buttons to try the
        # next button. But this is the only way I've found to make
        # the GTK Entry actually change to the new font;
        # without it, it changes maybe 1/3 of the time.
        # Also, this is the only way I've found to keep the text
        # from being all selected. You'd think that
        # self.preview.select_region(0, 0)
        # would do that, but it doesn't.
        # (See https://stackoverflow.com/q/20225691 for discussion.)
        self.preview.grab_focus_without_selecting()

        # Heroic efforts to keep font changes in the Entry from
        # making the whole window resize every time.
        # GTK offers no way to say "make the damn entry stay the same size."
        #self.allow_grow = False
        #self.set_property("allow-grow", False)
        alloc = self.preview.get_allocation()
        if alloc.width > 1 and alloc.height > 1:
            self.preview.set_size_request(alloc.width, alloc.height)

        # Used to use self.apply_CSS here, but it doesn't handle
        # font faces, just families.

        self.update_category_buttons(family.get_name())

        # Now that we're done changing things,
        # allow resizing from the user again:
        # Unfortunately this is still too early: the entry still resizes!
        # So for now, live with the user not being able to resize smaller.
        #self.preview.set_size_request(-1, -1)

    @staticmethod
    def facename_key(face):
        facename = face.get_face_name()
        words = facename.split()
        lastword = words[-1]
        if lastword == "Normal":
            lastword = '0 ' + lastword
        elif lastword == "Regular":
            lastword = '1 ' + lastword

        return lastword + ' ' + ' '.join(words)

    def choose_family(self, widget, familyname=None):
        self.fontsize = self.sizespin.get_value()
        if not familyname:
            familyname = self.get_cur_font_family()
        if not familyname:
            return

        # Show buttons for faces within this family (bold, italic etc.)
        font_family = self.font_families[familyname]
        if not font_family:
            print("eek, font families not initialized yet")
            return

        self.update_category_buttons(familyname)

        # font_family.list_faces() may have lots of repeats:
        # for instance, JetBrains Mono has two of almost every item.
        # So iterate through it looking for repeats.
        self.faces = []
        facenames = []
        basebutton = None
        # baseindex is only for debugging and should be removed later
        baseindex = None

        i = 0
        for face in sorted(font_family.list_faces(),
                           key=FontasiaApp.facename_key):
            facename = face.get_face_name()
            if facename in facenames:
                # A lot of fonts have repeated face names
                # print(familyname, ": skipping duplicate face", facename)
                continue
            if i >= MAX_FACES:
                # print("eek! Too many face names", len(self.faces))
                # print("Truncated to", ', '.join([f.get_face_name()
                #                                  for f in self.faces]))
                break

            facenames.append(facename)
            self.faces.append(face)
            if i < len(self.facebuttons):  # already exists; change its name
                btn = self.facebuttons[i]
                btn.set_label(facename)
            else:                          # Make a new button
                btn = Gtk.ToggleButton(label=facename)
                btn.set_active(False)
                btn.connect("toggled", self.facebutton_cb, i)

                self.facebuttons.append(btn)
                self.facebuttonbox.insert(btn, position=-1)

            lface = facename.lower()
            if lface == "normal":
                basebutton = btn
                baseindex = i
            elif lface == "regular":
                basebutton = btn
                baseindex = i

            i += 1

            btn.show()

        # hide the unused high-number buttons.
        # How I wish there was a way to change button states without
        # triggering callbacks every time!
        self.ignore_callbacks = True
        for j, btn in enumerate(self.facebuttons[i:]):
            index = i + j
            btn.hide()
            if btn.get_active():
                btn.set_active(False)
        self.ignore_callbacks = False

        if not basebutton and self.faces:
            basebutton = self.facebuttons[0]
            baseindex = 0

        if basebutton:
            # set_active() is documented to call the callback,
            # but facebutton_cb is never called here.
            basebutton.set_active(True)
            # so call it explicitly:
            self.facebutton_cb(basebutton, baseindex)
        else:
            self.render_font(font_family, None)

    def facebutton_cb(self, button, index):
        if self.ignore_callbacks:
            return
        if not self.get_cur_font_family():
            return

        family = self.font_families[self.get_cur_font_family()]
        face = self.faces[index]

        # Toggle off all the other buttons.
        # It might be nice to use Gtk.RadioButton, but those
        # don't look as good for this application and the docs
        # are pretty unclear about how to set them up.
        self.ignore_callbacks = True
        for i, btn in enumerate(self.facebuttons):
            if i != index:
                btn.set_active(False)

        self.render_font(family, face)
        self.ignore_callbacks = False

    def show_all_categories(self, widget):
        for btn in self.category_buttons:
            btn.set_active(False)
        self.update_font_list()


    def get_font_languages(self):
        """Get a list of all fonts and their languages by shelling out
           to fc-list, since there's no way to get this info from Pango.
           Return a dictionary 'family name': { set of 2-letter language codes }
        """
        # Fontconfig tags each font with an FC_LANG property,
        # a set of ISO 639 language codes it covers
        out = subprocess.run(
            ["fc-list", "--format", "%{family[0]}\t%{lang}\n"],
            capture_output=True, text=True, check=True
        ).stdout

        self.langs_by_family = {}
        for line in out.splitlines():
            if not line.strip() or "\t" not in line:
                continue
            family, langs = line.split("\t", 1)
            if family not in self.langs_by_family:
                self.langs_by_family[family] = set()
            if langs:
                langs = langs.split("|")
                self.langs_by_family[family] |= set(langs)


class PersistentCheckMenuItem(Gtk.CheckMenuItem):
    """A CheckMenuItem that toggles without closing the parent menu."""

    def __init__(self, label):
        super().__init__(label=label)
        self.connect("button-release-event", self._on_button_release)

    def _on_button_release(self, item, event):
        self.set_active(not self.get_active())  # still fires "toggled"
        return True  # stop propagation -> menu shell won't auto-popdown


class ToggleOptionsMenu(Gtk.Button):
    """A button that pops up a scrollable list of check buttons.
       options is a list of (shortname, prettyname)
       or (shortname, prettyname, true) for options that should be toggled on.
       When the menu is popped down, presumably after changing something,
       call on_changed (passing no arguments).
       The caller can get the list of currently ON toggles
       with get_active_list().
    """

    def __init__(self, options, on_changed=None, max_visible=8):
        super().__init__(label="All")
        self.on_changed = on_changed
        self.items = {}
        self.connect("clicked", self._on_clicked)

        self.popup = Gtk.Window(type=Gtk.WindowType.POPUP)
        self.popup.set_type_hint(Gdk.WindowTypeHint.POPUP_MENU)
        self.popup.connect("button-press-event", self._on_popup_button_press)
        self.popup.connect("key-press-event", self._on_popup_key_press)
        self.popup.connect("grab-broken-event", lambda *a: self._popdown())

        scrolled = Gtk.ScrolledWindow()
        scrolled.set_policy(Gtk.PolicyType.NEVER, Gtk.PolicyType.AUTOMATIC)

        box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=0)
        box.set_border_width(4)
        for key, label in options:
            btn = Gtk.CheckButton(label=label)
            btn.set_relief(Gtk.ReliefStyle.NONE)
            box.pack_start(btn, False, False, 0)
            self.items[key] = btn
        box.show_all()

        scrolled.add(box)
        self.popup.add(scrolled)

        # Cap the popup's height so it scrolls after max_visible rows
        # instead of growing to fit every item. Approximate row height
        # from one button; nudge max_visible/row_height if it's off.
        row_height = box.get_preferred_height()[1] // max(len(options), 1)
        scrolled.set_min_content_height(min(len(options),
                                            max_visible) * row_height)
        scrolled.set_max_content_height(max_visible * row_height)
        scrolled.set_propagate_natural_height(True)

    def set_options(self, optionlist):
        for key in self.items:
            for opt in optionlist:
                if key == opt:
                    self.items[key].set_active(True)
        self.update_title()

    def _on_clicked(self, button):
        if self.popup.get_visible():
            self._popdown()
        else:
            self._popup()

    def _popup(self):
        window = self.get_window()
        alloc = self.get_allocation()
        x, y = window.get_root_coords(alloc.x, alloc.y)
        self.popup.move(x, y + alloc.height)
        self.popup.set_size_request(alloc.width, -1)
        self.popup.show_all()
        # Explicitly focus it so it actually receives key events (Escape) --
        # override-redirect popups aren't given focus by the WM automatically.
        self.popup.get_window().focus(Gdk.CURRENT_TIME)
        self._grab()
        self.popup.grab_add()

    def _popdown(self):
        self._ungrab()
        self.popup.grab_remove()
        self.popup.hide()
        self.update_title()

    def update_title(self):
        active_items = [ key for key in self.items
                         if self.items[key].get_active() ]
        title = ','.join([ self.items[key].get_label()
                           for key in active_items ])
        if not title:
            title = "All"
        self.set_label(title)

        if self.on_changed:
            self.on_changed()

    def _grab(self):
        seat = Gdk.Display.get_default().get_default_seat()
        seat.grab(
            self.popup.get_window(),
            Gdk.SeatCapabilities.ALL,
            True,  # owner_events: clicks inside the popup still reach its widgets
            None, None, None, None,
        )

    def _ungrab(self):
        Gdk.Display.get_default().get_default_seat().ungrab()

    def _on_popup_button_press(self, widget, event):
        # Anything outside the popup's on-screen rectangle counts as "outside".
        px, py = self.popup.get_position()
        pw, ph = self.popup.get_size()
        if not (px <= event.x_root <= px + pw and py <= event.y_root <= py + ph):
            self._popdown()
            return True
        return False

    def _on_popup_key_press(self, widget, event):
        if event.keyval == Gdk.KEY_Escape:
            self._popdown()
            return True
        return False

    def set_active(self, key, active=True):
        self.items[key].set_active(active)

    def get_active_list(self):
        return [ key for key in self.items
                 if self.items[key].get_active() ]


def python_fu_fontasia():
    fontwin = FontasiaApp()

    # fontwin.connect("destroy", Gtk.main_quit)
    # Gtk.main()

    while not fontwin.quit:
        Gtk.main_iteration()

    pdb.gimp_context_set_font(fontwin.current_font())

if __name__ == '__main__':
    import sys
    # Are we being run as a GIMP plug-in?
    if sys.argv[0].endswith("gimp"):
        from gimpfu import *

        register(
            "python_fu_fontasia",
            "An alternate font chooser.",
            "An alternate font chooser.",
            "Akkana Peck",
            "Akkana Peck",
            "2016-2023",
            "Fontasia...",
            "",
            [
                # No arguments
            ],
            [],
            python_fu_fontasia,
            menu = "<Image>/Windows/"
        )

        # Call GIMP's main loop, which will call python_fu_fontasia
        # and handle cleaning up afterward.
        main()
        sys.exit(0)

    # Run in background, give control back to the calling shell.
    # Grr: GTK doesn't allow this any more.
    # rc = os.fork()
    # if rc:
    #     sys.exit(0)

    fontwin = FontasiaApp()
    while not fontwin.quit:
        Gtk.main_iteration()
    # Trust that the FontasiaApp has already saved new categories, etc.
    sys.exit(0)
