#! /usr/bin/env python3

# Search for IP clients on the current network.
# Only tested on Linux; requires ping or the Linux arguments for arp.
# ipsearch with no arguments uses ping; it takes a while but should be reliable.
# ipsearch -a uses arp only, which is fast but only shows
# hosts in the arp cache.

import sys
import subprocess
import socket
import fcntl
import struct
import re
import argparse

try:
    from arpreq import arpreq
except:
    arpreq = None

try:
    from mac_lookup import match_mac
except:
    match_mac = None

gDebugging = False

def ping(host):
    """Ping a host by name or address.
       return True if it answers, False otherwise.
    """
    rv = subprocess.call(["ping", "-q", "-c", "1", "-W", "1", host],
                         stdout = subprocess.PIPE,
                         stderr = subprocess.PIPE)
    if rv == 0:
        return ""
    return None

def check_port(host, port):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(.25)
    result = sock.connect_ex((host, port))
    sock.close()
    return not result

def arp(host):
    """Call arp -a on an address.
       return True if it answers, False otherwise.
    """
    # print("host", host)
    proc = subprocess.Popen(["arp", "-a", host],
                         stdout = subprocess.PIPE,
                         stderr = subprocess.PIPE)
    proc_out = proc.communicate()[0].strip()
    # print("proc_out is '%s'" % proc_out)
    if b"no match found" in proc_out:
        # print("no match found, returning none")
        return None
    # else:
    #     print("'no match found' isn't in '%s'" % proc_out)
    if b"<incomplete>" in proc_out:
        return None

    match = re.search(b'([0-9A-F]{2}[:-]){5}([0-9A-F]{2})', proc_out, re.I)
    if match:
        return match.group().decode("utf-8")
    return None

def ip_addr(iface):
    """Get the IP address of the interface (e.g. eth0)
    """
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    info = fcntl.ioctl(s.fileno(),
                       0x8915,  # SIOCGIFADDR
                       struct.pack('256s', bytes(iface[:15], "utf-8")))
    return socket.inet_ntoa(info[20:24])

def scan(iface="eth0", ping_fn=ping, ping_first=True, port=None):
    myip = ip_addr(iface)
    mynetwork = '.'.join(myip.split('.')[0:3])

    if (gDebugging):
        print("My IP is", myip, "on", iface)
        print("My network is", mynetwork)

    fmt = "%15s %18s %12s %s"

    for h in range(1, 255):  # I know, it should adjust based on net class
        hostip = "%s.%d" % (mynetwork, h)
        sys.stdout.flush()

        if gDebugging:
            print(hostip, end='\r')
            sys.stdout.flush()

        if port:
            if not check_port(hostip, port):
                sys.stdout.flush()
                continue
            sys.stdout.flush()

        if ping_first:
            out = ping_fn(hostip)

        if arpreq:
            mac = arpreq(hostip)
        else:
            mac = arp(hostip)

        if not mac:
            continue

        if match_mac:
            oui = match_mac(mac)
        else:
            oui = ''

        try:
            hostname, blah1, blah2 = socket.gethostbyaddr(hostip)
        except:
            hostname = '?'

        if hostip == myip:
            print(fmt % (hostip, mac, hostname, oui), "(that's me)")
        else:
            print(fmt % (hostip, mac, hostname, oui))

if __name__ == "__main__":
    def Usage():
        print("""Usage: %s [-a] [-p]
-p: ping each host first, in case they weren't in the arp cache already
-a: Use arp -a to ping.
""" % sys.argv[0])
        sys.exit(1)

    ifaces = [ "eth0", "wlan0" ]
    myip = None

    for iface in ifaces:
        try:
            myip = ip_addr(iface)
            break
        except OSError:
            continue

    if not myip:
        print("Couldn't find my IP address")
        sys.exit(1)

    parser = argparse.ArgumentParser()

    parser.add_argument('-a', "--arpa", dest="arpa", default=False,
                        action="store_true", help="Use arp -a to ping")
    parser.add_argument('-P', "--ping", dest="pingfirst", default=False,
                        action="store_true", help="Ping each host first")
    parser.add_argument('-d', "--debug", dest="debug", default=False,
                        action="store_true", help="Verbose debugging")

    parser.add_argument('-p', action="store", dest="port", type=int,
                        default=None, help='Check if this port is open')

    args = parser.parse_args(sys.argv[1:])
    if args.debug:
        gDebugging = True

    try:
        if args.port:
            scan(iface, port=args.port)
        elif args.arpa:
            scan(iface, arp)
        elif args.pingfirst:
            scan(iface, ping_first=False)
        else:
            scan(iface)

    except KeyboardInterrupt:
        print("Interrupt")
