#!/bin/bash

# A quickie way to switch audio between internal speakers and a USB hub,
# using pulseaudio commandline tools.

# Adjust as needed for your specific audio devices.
# To see your available audio devices: pacmd list-cards
# For each card, look under "profiles:"

#
# SOME PULSEAUDIO NOTES:
#
# https://brokkr.net/2018/05/24/down-the-drain-the-elusive-default-pulseaudio-sink/
# has some great info on pulseaudio fallbacks:
# pacmd list-sinks | grep -e 'name:' -e 'index'
# puts an asterisk in front of the fallback.
# There are also some  old comments claiming that you can
# export PULSE_SINK="sink_name"
# export PULSE_SOURCE="source_name"
# Get the names with
# LANG=C pactl list | grep -A3 'Sink #'
# then, e.g.,
#   PULSE_SINK='alsa_output.usb-0c76_USB_PnP_Audio_Device-00.analog-stereo' musicplayer
#   PULSE_SINK='alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink' musicplayer
# In theory, Set the default by noting the index of the sink you want, then
#   pacmd set-default-sink 1
# In practice that doesn't work. Maybe it would after editing
# /etc/pulse/default.pa to set:
#   load-module module-stream-restore restore_device=false
#
# Change a running stream to a different sink:
#   pacmd list-sink-inputs
#   pacmd move-sink-input 5 1

internal_i=$(pactl list short cards | grep pci | awk '{ print $1 }')
hub_i=$(pactl list short cards | grep USB_PnP_Audio_Device | awk '{ print $1 }')

if [[ $1 == 'hub' ]]; then
    echo "Directing audio to USB hub"
    pactl set-card-profile $internal_i off
    if [[ ! -z $hub_i ]]; then
        pactl set-card-profile $hub_i output:analog-stereo
    fi

elif [[ $1 == 'hubmic' ]]; then
    echo "Directing audio to USB hub with mic enabled"
    pactl set-card-profile $internal_i off
    if [[ ! -z $hub_i ]]; then
        pactl set-card-profile $hub_i output:analog-surround-40+input:analog-stereo
    fi

elif [[ $1 == 'int' ]]; then
    echo "Directing audio to internal speakers"
    if [[ ! -z $hub_i ]]; then
        pactl set-card-profile $hub_i off
    fi
    # Carbon X1 on Ubuntu eoan:
    # pactl set-card-profile $internal_i output:analog-stereo
    # Carbon X1 on Ubuntu fossa:
    pactl set-card-profile $internal_i HiFi

elif [[ $1 == 'intmic' ]]; then
    echo "Directing audio to internal speakers with mic enabled"
    if [[ ! -z $hub_i ]]; then
        pactl set-card-profile $hub_i off
    fi
    # Carbon X1 on Ubuntu eoan:
    pactl set-card-profile $internal_i output:analog-surround-40+input:analog-stereo
    # Carbon X1 on Ubuntu fossa:
    pactl set-card-profile $internal_i HiFi

else
    echo 'Usage: pulse [hub|int|hubmic|intmic]'
fi
