#!/usr/bin/env python2

import gtk
import re

primary = gtk.clipboard_get(gtk.gdk.SELECTION_PRIMARY)

if not primary.wait_is_text_available() :
    sys.exit(0)

s = primary.wait_for_text()

# If it's a LinkedIn URL, fix their stupid errors:
if re.search('(www\.)*linkedin.com/', s, flags=re.IGNORECASE):
    s = s.replace("&amp;", "&") + "&count=1000&paginationToken="

# eliminate newlines, and any spaces immediately following a newline:
print(re.sub(r'[\r\n]+ *', '', s))

