#!/usr/bin/env python

# randomline: echo one line, randomly chosen, from stdin.
# Copyright 2007 Akkana Peck, GPL blah blah, free to reuse blah blah
#
# Thanks to saz and http://www.goldfish.org/books/O'Reilly%20Perl%20CD%20Bookshelf%202.0/cookbook/ch08_07.htm
# for the cute algorithm.

from __future__ import print_function

import sys
import random

def randomline(fp):
    num_lines = 0
    picked = ""
    #for line in fp:
    while True:
        line = fp.readline()
        line = line.strip()
        if not line : break
        num_lines += 1
        if random.randint(1, num_lines) == 1 :
            return line

    # In the unlikely case random didn't give anything, return the last line.
    return line

if __name__ == '__main__':
    random.seed()

    fp = open(sys.argv[1]) if len(sys.argv) > 1 else sys.stdin
    print(randomline(fp))










'''
import sys, string, random

# main

random.seed()
num_lines = 0
picked = ""
while 1 :
    line = sys.stdin.readline()
    if not line : break
    line = string.strip(line, " \n")
    if line == '' : continue
    num_lines += 1
    if random.randint(1, num_lines) == 1 :
        picked = line

print(picked)

'''
