#! /usr/bin/env python

import sys

# Display the colors available in a terminal.
#  given any argument, it'll display 256-color mode as well as 16-color mode.

# Programs like ls and vim use the first 16 colors of the 256-color palette.
# This was documented as 16-color mode, but actually anything over 8 fails.
if len(sys.argv) > 1:
    print("256-color mode:")
    for color in range(0, 256) :
        line = ""
        # print several copies to make it easier to see the color
        for i in range(0, 5) :
            line += "\033[38;5; %sm %03s\033[m" % (str(color), str(color))
        print(line)
    print()
    print("16-color mode (actually only 8):")
else:
    print("16-color mode (actually only 8): use -256 to usee more colors.")

colornames = [ "black", "red", "green", "yellow",
               "blue", "magenta", "cyan", "white" ]
print("    %14ss %14s %14ss" % ('normal', 'inverse', 'bright'))
for color in range(0, 8) :
    line = ""

    # Print the color in normal and inverse video:
    for prefix in [3, 4] :
        line += "\033[0;%s%dm%2d%2d%2d %-8s\033[m " % (prefix, color,
                                                       color, color, color,
                                                       colornames[color])
    # Also print the "bright" version of the color:
    for prefix in [3] :
        line += "\033[0;%s%d;1m%2d%2d%2d %-8s\033[m " % (prefix, color,
                                                         color, color, color,
                                                         colornames[color])
    print(line)

# Extra credit: display other formatting
print()
print('Styles: \033[1mbold\033[0m '
      '\033[3mitalic\033[0m '
      '\033[4munderline\033[0m '
      '033[9mstrikethrough\033[0m '
      '\033[31mred\033[0m\n')

if len(sys.argv) > 1 and sys.argv[1] == '-all':
    # Text styles like bold:
    # https://stackoverflow.com/a/33206814

    print()
    print("\033[1mEffects:\033[m")
    print("\\033[4m  Underline on")
    print("\\033[24m Underline off")
    print("\\033[1m  Bold on")
    print("\\033[21m Bold off")

    # Cursor movement
    print()
    print("\033[1mMovement:\033[m")
    print("\033[39m\\033[39m - Reset colour")
    print("\\033[2K - Clear Line")
    print("\\033[<L>;<C>H OR \\033[<L>;<C>f puts the cursor at line L and column C.")
    print("\\033[<N>A Move the cursor up N lines")
    print("\\033[<N>B Move the cursor down N lines")
    print("\\033[<N>C Move the cursor forward N columns")
    print("\\033[<N>D Move the cursor backward N columns")
    print("\\033[2J Clear the screen, move to (0,0)")
    print("\\033[K Erase to end of line")
    print("\\033[s Save cursor position")
    print("\\033[u Restore cursor position")
