#!/usr/bin/env python

# Simple volume control.
# Because I'm tired of gnome-volume-control changing names or
# removing features every time I turn around, and no one else
# seems to be interested in writing a basic volume control app
# that isn't a windowmanager panel applet.

# Copyright 2005 by Akkana Peck.
# You may use, distribute, or modify this program under the terms of the GPL.

import string, re, os, sys

import alsaaudio

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk as gtk

def Usage() :
    print("Usage: %s [-v|-h]" % os.path.basename(sys.argv[0]))
    sys.exit(0)

# First find a mixer. Use the first one.
try :
    mixer = alsaaudio.Mixer('Master', 0)
except alsaaudio.ALSAAudioError :
    sys.stderr.write("No such mixer\n")
    sys.exit(1)

# Get the current system volume.
def get_volume() :
    return mixer.getvolume()[0]

# Change the system volume (both channels at once).
def change_volume(scale) :
    newval = int(scale.get_adjustment().value)
    mixer.setvolume(newval, alsaaudio.MIXER_CHANNEL_ALL)

def key_press(w, event) :
    if event.string == "q" :
        sys.exit(0)
    return False

def create_window(vol, verticalP) :
    win = gtk.Window()
    win.set_name("PyVolume")
    win.set_border_width(5)
    win.connect("destroy", gtk.main_quit)

    vbox = gtk.VBox()
    win.add(vbox)

    adj = gtk.Adjustment(value=vol, lower=0, upper=100,
                         step_incr=-1, page_incr=6)
    if (vertical) :
        scale = gtk.VScale(adjustment=adj)
        scale.set_size_request(50, 250)
    else :
        scale = gtk.HScale(adjustment=adj)
        scale.set_size_request(250, 50)
    scale.set_digits(0)
    vbox.pack_start(scale, False, False, 0)
    scale.show()
    vbox.show()

    scale.connect("value_changed", change_volume)
    scale.connect("key-press-event", key_press)

    win.show()
    gtk.main()

# main
vertical = 0
if len(sys.argv) > 1:
    if sys.argv[1] in ["-v", "-V"]:
        vertical = 1
    elif sys.argv[1] != "-h" :
        Usage()

create_window(get_volume(), vertical)

