#!/usr/bin/env python

# Weather from wunderground.
# Needs an API key, which is a pain in the butt to get even for the free one.


import urllib2
import json
from pprint import pprint

def find_nearby_stations(wundata):
    '''Extract the nearby stations info in the wunderground data
       into a sorted list.
    '''
    nearby = []

    # Ignore the list of official airport stations,
    # wundata['location']['nearby_weather_stations']['airport']['station']
    # since it doesn't give distance for those, and we can get them
    # from other sites anyway.

    for station in wundata['location']['nearby_weather_stations']['pws']['station']:
        nearby.append((int(station['distance_mi']), station))

    return nearby

f = urllib2.urlopen('http://api.wunderground.com/api/15353acd8a8c2a1f/geolookup/conditions/q/NM/White_Rock.json')
json_string = f.read()
f.close()
wundata = json.loads(json_string)
# pprint(wundata)
location = wundata['location']['city']
temp_f = wundata['current_observation']['temp_f']
print "Current temperature in %s is: %s" % (location, temp_f)
print
print "Nearby weather stations:",
#nearby = find_nearby_stations(wundata)
for station in wundata['location']['nearby_weather_stations']['pws']['station']:
    #print station
    print "%12s: %12s: %-50s (%s mi)" % (station['id'], station['city'],
                                   station['neighborhood'],
                                   station['distance_mi'])

'''
<hesiodus>- wunderwx.py
{u'current_observation': {u'UV': u'0',
                          u'dewpoint_c': 4,
                          u'dewpoint_f': 40,
                          u'dewpoint_string': u'40 F (4 C)',
                          u'display_location': {u'city': u'White Rock',
                                                u'country': u'US',
                                                u'country_iso3166': u'US',
                                                u'elevation': u'2136.00000000',
                                                u'full': u'White Rock, NM',
                                                u'latitude': u'35.86780548',
                                                u'longitude': u'-106.26818848',
                                                u'magic': u'2',
                                                u'state': u'NM',
                                                u'state_name': u'New Mexico',
                                                u'wmo': u'99999',
                                                u'zip': u'87544'},
                          u'estimated': {},
                          u'feelslike_c': u'19.2',
                          u'feelslike_f': u'66.6',
                          u'feelslike_string': u'66.6 F (19.2 C)',
                          u'forecast_url': u'http://www.wunderground.com/US/NM/White_Rock.html',
                          u'heat_index_c': u'NA',
                          u'heat_index_f': u'NA',
                          u'heat_index_string': u'NA',
                          u'history_url': u'http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KNMLOSAL6',
                          u'icon': u'clear',
                          u'icon_url': u'http://icons-ak.wxug.com/i/c/k/nt_clear.gif',
                          u'image': {u'link': u'http://www.wunderground.com',
                                     u'title': u'Weather Underground',
                                     u'url': u'http://icons-ak.wxug.com/graphics/wu2/logo_130x80.png'},
                          u'local_epoch': u'1376540399',
                          u'local_time_rfc822': u'Wed, 14 Aug 2013 22:19:59 -0600',
                          u'local_tz_long': u'America/Denver',
                          u'local_tz_offset': u'-0600',
                          u'local_tz_short': u'MDT',
                          u'ob_url': u'http://www.wunderground.com/cgi-bin/findweather/getForecast?query=35.896976,-106.260284',
                          u'observation_epoch': u'1376540155',
                          u'observation_location': {u'city': u'Otowi Mesa, Los Alamos',
                                                    u'country': u'US',
                                                    u'country_iso3166': u'US',
                                                    u'elevation': u'7170 ft',
                                                    u'full': u'Otowi Mesa, Los Alamos, New Mexico',
                                                    u'latitude': u'35.896976',
                                                    u'longitude': u'-106.260284',
                                                    u'state': u'New Mexico'},
                          u'observation_time': u'Last Updated on August 14, 10:15 PM MDT',
                          u'observation_time_rfc822': u'Wed, 14 Aug 2013 22:15:55 -0600',
                          u'precip_1hr_in': u'-999.00',
                          u'precip_1hr_metric': u' 0',
                          u'precip_1hr_string': u'-999.00 in ( 0 mm)',
                          u'precip_today_in': u'0.00',
                          u'precip_today_metric': u'0',
                          u'precip_today_string': u'0.00 in (0 mm)',
                          u'pressure_in': u'30.35',
                          u'pressure_mb': u'1028',
                          u'pressure_trend': u'-',
                          u'relative_humidity': u'38%',
                          u'solarradiation': u'0',
                          u'station_id': u'KNMLOSAL6',
                          u'temp_c': 19.2,
                          u'temp_f': 66.6,
                          u'temperature_string': u'66.6 F (19.2 C)',
                          u'visibility_km': u'16.1',
                          u'visibility_mi': u'10.0',
                          u'weather': u'Clear',
                          u'wind_degrees': 140,
                          u'wind_dir': u'SE',
                          u'wind_gust_kph': 0,
                          u'wind_gust_mph': 0,
                          u'wind_kph': 0.0,
                          u'wind_mph': 0.0,
                          u'wind_string': u'Calm',
                          u'windchill_c': u'NA',
                          u'windchill_f': u'NA',
                          u'windchill_string': u'NA'},
 u'location': {u'city': u'White Rock',
               u'country': u'US',
               u'country_iso3166': u'US',
               u'country_name': u'USA',
               u'l': u'/q/zmw:87544.2.99999',
               u'lat': u'35.86780548',
               u'lon': u'-106.26818848',
               u'magic': u'2',
               u'nearby_weather_stations': {u'airport': {u'station': [{u'city': u'Los Alamos',
                                                                       u'country': u'US',
                                                                       u'icao': u'KLAM',
                                                                       u'lat': u'35.88000107',
                                                                       u'lon': u'-106.26999664',
                                                                       u'state': u'NM'},
                                                                      {u'city': u'Santa Fe',
                                                                       u'country': u'US',
                                                                       u'icao': u'KSAF',
                                                                       u'lat': u'35.61999893',
                                                                       u'lon': u'-106.08999634',
                                                                       u'state': u'NM'},
                                                                      {u'city': u'Cuba',
                                                                       u'country': u'US',
                                                                       u'icao': u'K4SL',
                                                                       u'lat': u'35.79999924',
                                                                       u'lon': u'-107.18000031',
                                                                       u'state': u'NM'},
                                                                      {u'city': u'Taos',
                                                                       u'country': u'US',
                                                                       u'icao': u'KSKX',
                                                                       u'lat': u'36.45999908',
                                                                       u'lon': u'-105.66999817',
                                                                       u'state': u'NM'}]},
                                            u'pws': {u'station': [{u'city': u'Los Alamos',
                                                                   u'country': u'US',
                                                                   u'distance_km': 3,
                                                                   u'distance_mi': 1,
                                                                   u'id': u'KNMLOSAL6',
                                                                   u'lat': 35.896976,
                                                                   u'lon': -106.260284,
                                                                   u'neighborhood': u'Otowi Mesa',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Los Alamos',
                                                                   u'country': u'US',
                                                                   u'distance_km': 3,
                                                                   u'distance_mi': 2,
                                                                   u'id': u'KNMSANTA31',
                                                                   u'lat': 35.900387,
                                                                   u'lon': -106.269043,
                                                                   u'neighborhood': u'Navajo Rd Barranca Mesa',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Los Alamos',
                                                                   u'country': u'US',
                                                                   u'distance_km': 3,
                                                                   u'distance_mi': 2,
                                                                   u'id': u'KNMLOSAL7',
                                                                   u'lat': 35.900734,
                                                                   u'lon': -106.265678,
                                                                   u'neighborhood': u'Barranca Mesa',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Los Alamos',
                                                                   u'country': u'US',
                                                                   u'distance_km': 4,
                                                                   u'distance_mi': 2,
                                                                   u'id': u'MD5852',
                                                                   u'lat': 35.904171,
                                                                   u'lon': -106.27417,
                                                                   u'neighborhood': u'APRSWXNET Los Alamos NM US',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Los Alamos',
                                                                   u'country': u'US',
                                                                   u'distance_km': 5,
                                                                   u'distance_mi': 3,
                                                                   u'id': u'KNMLOSAL13',
                                                                   u'lat': 35.885479,
                                                                   u'lon': -106.319977,
                                                                   u'neighborhood': u'UNMLA',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Los Alamos',
                                                                   u'country': u'US',
                                                                   u'distance_km': 5,
                                                                   u'distance_mi': 3,
                                                                   u'id': u'KNMLOSAL11',
                                                                   u'lat': 35.891136,
                                                                   u'lon': -106.327721,
                                                                   u'neighborhood': u'Quemazon',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Los Alamos',
                                                                   u'country': u'US',
                                                                   u'distance_km': 6,
                                                                   u'distance_mi': 3,
                                                                   u'id': u'MNFEN5',
                                                                   u'lat': 35.824501,
                                                                   u'lon': -106.317802,
                                                                   u'neighborhood': u'HADS BANDELIER NM SANTA FE 20 WNW NM US',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'White Rock',
                                                                   u'country': u'US',
                                                                   u'distance_km': 6,
                                                                   u'distance_mi': 4,
                                                                   u'id': u'KNMWHITE1',
                                                                   u'lat': 35.821667,
                                                                   u'lon': -106.220497,
                                                                   u'neighborhood': u'Alta Vista in White Rock',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'White Rock',
                                                                   u'country': u'US',
                                                                   u'distance_km': 7,
                                                                   u'distance_mi': 4,
                                                                   u'id': u'KNMWHITE3',
                                                                   u'lat': 35.817249,
                                                                   u'lon': -106.217857,
                                                                   u'neighborhood': u'',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Los Alamos',
                                                                   u'country': u'US',
                                                                   u'distance_km': 7,
                                                                   u'distance_mi': 4,
                                                                   u'id': u'KNMLOSAL1',
                                                                   u'lat': 35.808613,
                                                                   u'lon': -106.221382,
                                                                   u'neighborhood': u'',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'White Rock',
                                                                   u'country': u'US',
                                                                   u'distance_km': 7,
                                                                   u'distance_mi': 4,
                                                                   u'id': u'KNMWHITE4',
                                                                   u'lat': 35.820881,
                                                                   u'lon': -106.201149,
                                                                   u'neighborhood': u'Ridgecrest Ave',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Los Alamos',
                                                                   u'country': u'US',
                                                                   u'distance_km': 8,
                                                                   u'distance_mi': 5,
                                                                   u'id': u'KNMLOSAL12',
                                                                   u'lat': 35.802769,
                                                                   u'lon': -106.208878,
                                                                   u'neighborhood': u'Pajarito Arces',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Los Alamos',
                                                                   u'country': u'US',
                                                                   u'distance_km': 9,
                                                                   u'distance_mi': 5,
                                                                   u'id': u'MTWRN5',
                                                                   u'lat': 35.778988,
                                                                   u'lon': -106.266113,
                                                                   u'neighborhood': u'RAWS TOWER NM US',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Los Alamos',
                                                                   u'country': u'US',
                                                                   u'distance_km': 14,
                                                                   u'distance_mi': 8,
                                                                   u'id': u'MVLPS',
                                                                   u'lat': 35.915829,
                                                                   u'lon': -106.422783,
                                                                   u'neighborhood': u'MesoWest Los Posos (Valles Caldera) NM US DRI',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Los Alamos',
                                                                   u'country': u'US',
                                                                   u'distance_km': 21,
                                                                   u'distance_mi': 12,
                                                                   u'id': u'MVVLL',
                                                                   u'lat': 35.973888,
                                                                   u'lon': -106.464722,
                                                                   u'neighborhood': u'MesoWest Valle Toledo (Valles Caldera) NM US DRI',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Jemez Springs',
                                                                   u'country': u'US',
                                                                   u'distance_km': 22,
                                                                   u'distance_mi': 13,
                                                                   u'id': u'MVHVC',
                                                                   u'lat': 35.852779,
                                                                   u'lon': -106.521111,
                                                                   u'neighborhood': u'MesoWest Headquarters (Valles Caldera) NM US DRI',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Espanola',
                                                                   u'country': u'US',
                                                                   u'distance_km': 24,
                                                                   u'distance_mi': 14,
                                                                   u'id': u'KNMESPAN3',
                                                                   u'lat': 36.003834,
                                                                   u'lon': -106.047684,
                                                                   u'neighborhood': u'Fairview- Prof D',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Jemez Springs',
                                                                   u'country': u'US',
                                                                   u'distance_km': 25,
                                                                   u'distance_mi': 15,
                                                                   u'id': u'MVRDD',
                                                                   u'lat': 35.883888,
                                                                   u'lon': -106.553612,
                                                                   u'neighborhood': u'MesoWest Redondo (Valles Caldera) NM US DRI',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Santa Fe',
                                                                   u'country': u'US',
                                                                   u'distance_km': 27,
                                                                   u'distance_mi': 16,
                                                                   u'id': u'KNMSANTA35',
                                                                   u'lat': 35.73711,
                                                                   u'lon': -106.011299,
                                                                   u'neighborhood': u'Los Colibries',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Gallina',
                                                                   u'country': u'US',
                                                                   u'distance_km': 29,
                                                                   u'distance_mi': 17,
                                                                   u'id': u'MVSNT',
                                                                   u'lat': 35.98056,
                                                                   u'lon': -106.570831,
                                                                   u'neighborhood': u'MesoWest San Antonio (Valles Caldera) NM US DRI',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Santa Fe',
                                                                   u'country': u'US',
                                                                   u'distance_km': 30,
                                                                   u'distance_mi': 18,
                                                                   u'id': u'KNMSANTA30',
                                                                   u'lat': 35.714367,
                                                                   u'lon': -105.989128,
                                                                   u'neighborhood': u'La Mariposa',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Tesuque',
                                                                   u'country': u'US',
                                                                   u'distance_km': 30,
                                                                   u'distance_mi': 18,
                                                                   u'id': u'KNMTESUQ3',
                                                                   u'lat': 35.781624,
                                                                   u'lon': -105.946198,
                                                                   u'neighborhood': u'Tesuque Fire District',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Ponderosa',
                                                                   u'country': u'US',
                                                                   u'distance_km': 31,
                                                                   u'distance_mi': 19,
                                                                   u'id': u'MJESN5',
                                                                   u'lat': 35.840557,
                                                                   u'lon': -106.61972,
                                                                   u'neighborhood': u'RAWS JEMEZ NM US',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Ponderosa',
                                                                   u'country': u'US',
                                                                   u'distance_km': 33,
                                                                   u'distance_mi': 19,
                                                                   u'id': u'MVCNJ',
                                                                   u'lat': 35.718048,
                                                                   u'lon': -106.586113,
                                                                   u'neighborhood': u'MesoWest Conejos (Valles Caldera) NM US DRI',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Santa Fe',
                                                                   u'country': u'US',
                                                                   u'distance_km': 33,
                                                                   u'distance_mi': 19,
                                                                   u'id': u'KNMSANTA45',
                                                                   u'lat': 35.630482,
                                                                   u'lon': -106.044563,
                                                                   u'neighborhood': u'Tierra Contenta',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Santa Fe',
                                                                   u'country': u'US',
                                                                   u'distance_km': 33,
                                                                   u'distance_mi': 20,
                                                                   u'id': u'KNMSANTA42',
                                                                   u'lat': 35.624863,
                                                                   u'lon': -106.043579,
                                                                   u'neighborhood': u'Agua Fria 2SW',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Santa Fe',
                                                                   u'country': u'US',
                                                                   u'distance_km': 33,
                                                                   u'distance_mi': 20,
                                                                   u'id': u'KNMSANTA40',
                                                                   u'lat': 35.693501,
                                                                   u'lon': -105.958664,
                                                                   u'neighborhood': u'Casa Solana',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Santa Fe',
                                                                   u'country': u'US',
                                                                   u'distance_km': 35,
                                                                   u'distance_mi': 21,
                                                                   u'id': u'KNMSANTA46',
                                                                   u'lat': 35.720001,
                                                                   u'lon': -105.919998,
                                                                   u'neighborhood': u'Circle Drive Compound',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Santa Fe',
                                                                   u'country': u'US',
                                                                   u'distance_km': 35,
                                                                   u'distance_mi': 21,
                                                                   u'id': u'KNMSANTA19',
                                                                   u'lat': 35.635605,
                                                                   u'lon': -105.999023,
                                                                   u'neighborhood': u'Southwest Santa Fe',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Santa Fe',
                                                                   u'country': u'US',
                                                                   u'distance_km': 35,
                                                                   u'distance_mi': 21,
                                                                   u'id': u'KNMSANTA33',
                                                                   u'lat': 35.69381,
                                                                   u'lon': -105.933571,
                                                                   u'neighborhood': u'Ft. Marcy',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Santa Fe',
                                                                   u'country': u'US',
                                                                   u'distance_km': 38,
                                                                   u'distance_mi': 23,
                                                                   u'id': u'KNMSANTA48',
                                                                   u'lat': 35.65379,
                                                                   u'lon': -105.926109,
                                                                   u'neighborhood': u'East Zia',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Jemez Springs',
                                                                   u'country': u'US',
                                                                   u'distance_km': 39,
                                                                   u'distance_mi': 23,
                                                                   u'id': u'MVJEM',
                                                                   u'lat': 35.77972,
                                                                   u'lon': -106.688889,
                                                                   u'neighborhood': u'MesoWest Jemez Springs (Valles Caldera) NM US DRI',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Abiquiu',
                                                                   u'country': u'US',
                                                                   u'distance_km': 39,
                                                                   u'distance_mi': 23,
                                                                   u'id': u'KNMABIQU3',
                                                                   u'lat': 36.224998,
                                                                   u'lon': -106.278442,
                                                                   u'neighborhood': u'Plaza Blanca',
                                                                   u'state': u'NM'},
                                                                  {u'city': u'Jemez Springs',
                                                                   u'country': u'US',
                                                                   u'distance_km': 39,
                                                                   u'distance_mi': 23,
                                                                   u'id': u'KNMJEMEZ2',
                                                                   u'lat': 35.766121,
                                                                   u'lon': -106.693016,
                                                                   u'neighborhood': u'Village of Jemez Springs',
                                                                   u'state': u'NM'}]}},
               u'requesturl': u'US/NM/White_Rock.html',
               u'state': u'NM',
               u'type': u'CITY',
               u'tz_long': u'America/Denver',
               u'tz_short': u'MDT',
               u'wmo': u'99999',
               u'wuiurl': u'http://www.wunderground.com/US/NM/White_Rock.html',
               u'zip': u'87544'},
 u'response': {u'features': {u'conditions': 1, u'geolookup': 1},
               u'termsofService': u'http://www.wunderground.com/weather/api/d/terms.html',
               u'version': u'0.1'}}
Current temperature in White Rock is: 66.6
'''
